/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkdirsIndexRouteImport } from './routes/workdirs/index'
import { Route as ApiWorkdirsRouteImport } from './routes/api/workdirs'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as WorkdirsWorkdirIdIndexRouteImport } from './routes/workdirs/$workdirId/index'
import { Route as ApiWorkdirsIdRouteImport } from './routes/api/workdirs.$id'
import { Route as ApiChatsIdRouteImport } from './routes/api/chats.$id'
import { Route as WorkdirsWorkdirIdChatsChatIdRouteImport } from './routes/workdirs/$workdirId/chats/$chatId'
import { Route as ApiWorkdirsIdUploadRouteImport } from './routes/api/workdirs.$id.upload'
import { Route as ApiWorkdirsIdManifestRouteImport } from './routes/api/workdirs.$id.manifest'
import { Route as ApiWorkdirsIdDownloadRouteImport } from './routes/api/workdirs.$id.download'
import { Route as ApiWorkdirsIdChatsRouteImport } from './routes/api/workdirs.$id.chats'
import { Route as ApiChatsChatIdStreamRouteImport } from './routes/api/chats.$chatId.stream'
import { Route as ApiChatsChatIdMessageRouteImport } from './routes/api/chats.$chatId.message'
import { Route as ApiChatsChatIdCancelRouteImport } from './routes/api/chats.$chatId.cancel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkdirsIndexRoute = WorkdirsIndexRouteImport.update({
  id: '/workdirs/',
  path: '/workdirs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkdirsRoute = ApiWorkdirsRouteImport.update({
  id: '/api/workdirs',
  path: '/api/workdirs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkdirsWorkdirIdIndexRoute = WorkdirsWorkdirIdIndexRouteImport.update({
  id: '/workdirs/$workdirId/',
  path: '/workdirs/$workdirId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkdirsIdRoute = ApiWorkdirsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkdirsRoute,
} as any)
const ApiChatsIdRoute = ApiChatsIdRouteImport.update({
  id: '/api/chats/$id',
  path: '/api/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkdirsWorkdirIdChatsChatIdRoute =
  WorkdirsWorkdirIdChatsChatIdRouteImport.update({
    id: '/workdirs/$workdirId/chats/$chatId',
    path: '/workdirs/$workdirId/chats/$chatId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkdirsIdUploadRoute = ApiWorkdirsIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiWorkdirsIdRoute,
} as any)
const ApiWorkdirsIdManifestRoute = ApiWorkdirsIdManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => ApiWorkdirsIdRoute,
} as any)
const ApiWorkdirsIdDownloadRoute = ApiWorkdirsIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiWorkdirsIdRoute,
} as any)
const ApiWorkdirsIdChatsRoute = ApiWorkdirsIdChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => ApiWorkdirsIdRoute,
} as any)
const ApiChatsChatIdStreamRoute = ApiChatsChatIdStreamRouteImport.update({
  id: '/api/chats/$chatId/stream',
  path: '/api/chats/$chatId/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsChatIdMessageRoute = ApiChatsChatIdMessageRouteImport.update({
  id: '/api/chats/$chatId/message',
  path: '/api/chats/$chatId/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatsChatIdCancelRoute = ApiChatsChatIdCancelRouteImport.update({
  id: '/api/chats/$chatId/cancel',
  path: '/api/chats/$chatId/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workdirs': typeof ApiWorkdirsRouteWithChildren
  '/workdirs/': typeof WorkdirsIndexRoute
  '/api/chats/$id': typeof ApiChatsIdRoute
  '/api/workdirs/$id': typeof ApiWorkdirsIdRouteWithChildren
  '/workdirs/$workdirId/': typeof WorkdirsWorkdirIdIndexRoute
  '/api/chats/$chatId/cancel': typeof ApiChatsChatIdCancelRoute
  '/api/chats/$chatId/message': typeof ApiChatsChatIdMessageRoute
  '/api/chats/$chatId/stream': typeof ApiChatsChatIdStreamRoute
  '/api/workdirs/$id/chats': typeof ApiWorkdirsIdChatsRoute
  '/api/workdirs/$id/download': typeof ApiWorkdirsIdDownloadRoute
  '/api/workdirs/$id/manifest': typeof ApiWorkdirsIdManifestRoute
  '/api/workdirs/$id/upload': typeof ApiWorkdirsIdUploadRoute
  '/workdirs/$workdirId/chats/$chatId': typeof WorkdirsWorkdirIdChatsChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workdirs': typeof ApiWorkdirsRouteWithChildren
  '/workdirs': typeof WorkdirsIndexRoute
  '/api/chats/$id': typeof ApiChatsIdRoute
  '/api/workdirs/$id': typeof ApiWorkdirsIdRouteWithChildren
  '/workdirs/$workdirId': typeof WorkdirsWorkdirIdIndexRoute
  '/api/chats/$chatId/cancel': typeof ApiChatsChatIdCancelRoute
  '/api/chats/$chatId/message': typeof ApiChatsChatIdMessageRoute
  '/api/chats/$chatId/stream': typeof ApiChatsChatIdStreamRoute
  '/api/workdirs/$id/chats': typeof ApiWorkdirsIdChatsRoute
  '/api/workdirs/$id/download': typeof ApiWorkdirsIdDownloadRoute
  '/api/workdirs/$id/manifest': typeof ApiWorkdirsIdManifestRoute
  '/api/workdirs/$id/upload': typeof ApiWorkdirsIdUploadRoute
  '/workdirs/$workdirId/chats/$chatId': typeof WorkdirsWorkdirIdChatsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/workdirs': typeof ApiWorkdirsRouteWithChildren
  '/workdirs/': typeof WorkdirsIndexRoute
  '/api/chats/$id': typeof ApiChatsIdRoute
  '/api/workdirs/$id': typeof ApiWorkdirsIdRouteWithChildren
  '/workdirs/$workdirId/': typeof WorkdirsWorkdirIdIndexRoute
  '/api/chats/$chatId/cancel': typeof ApiChatsChatIdCancelRoute
  '/api/chats/$chatId/message': typeof ApiChatsChatIdMessageRoute
  '/api/chats/$chatId/stream': typeof ApiChatsChatIdStreamRoute
  '/api/workdirs/$id/chats': typeof ApiWorkdirsIdChatsRoute
  '/api/workdirs/$id/download': typeof ApiWorkdirsIdDownloadRoute
  '/api/workdirs/$id/manifest': typeof ApiWorkdirsIdManifestRoute
  '/api/workdirs/$id/upload': typeof ApiWorkdirsIdUploadRoute
  '/workdirs/$workdirId/chats/$chatId': typeof WorkdirsWorkdirIdChatsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/workdirs'
    | '/workdirs/'
    | '/api/chats/$id'
    | '/api/workdirs/$id'
    | '/workdirs/$workdirId/'
    | '/api/chats/$chatId/cancel'
    | '/api/chats/$chatId/message'
    | '/api/chats/$chatId/stream'
    | '/api/workdirs/$id/chats'
    | '/api/workdirs/$id/download'
    | '/api/workdirs/$id/manifest'
    | '/api/workdirs/$id/upload'
    | '/workdirs/$workdirId/chats/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/workdirs'
    | '/workdirs'
    | '/api/chats/$id'
    | '/api/workdirs/$id'
    | '/workdirs/$workdirId'
    | '/api/chats/$chatId/cancel'
    | '/api/chats/$chatId/message'
    | '/api/chats/$chatId/stream'
    | '/api/workdirs/$id/chats'
    | '/api/workdirs/$id/download'
    | '/api/workdirs/$id/manifest'
    | '/api/workdirs/$id/upload'
    | '/workdirs/$workdirId/chats/$chatId'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/workdirs'
    | '/workdirs/'
    | '/api/chats/$id'
    | '/api/workdirs/$id'
    | '/workdirs/$workdirId/'
    | '/api/chats/$chatId/cancel'
    | '/api/chats/$chatId/message'
    | '/api/chats/$chatId/stream'
    | '/api/workdirs/$id/chats'
    | '/api/workdirs/$id/download'
    | '/api/workdirs/$id/manifest'
    | '/api/workdirs/$id/upload'
    | '/workdirs/$workdirId/chats/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWorkdirsRoute: typeof ApiWorkdirsRouteWithChildren
  WorkdirsIndexRoute: typeof WorkdirsIndexRoute
  ApiChatsIdRoute: typeof ApiChatsIdRoute
  WorkdirsWorkdirIdIndexRoute: typeof WorkdirsWorkdirIdIndexRoute
  ApiChatsChatIdCancelRoute: typeof ApiChatsChatIdCancelRoute
  ApiChatsChatIdMessageRoute: typeof ApiChatsChatIdMessageRoute
  ApiChatsChatIdStreamRoute: typeof ApiChatsChatIdStreamRoute
  WorkdirsWorkdirIdChatsChatIdRoute: typeof WorkdirsWorkdirIdChatsChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workdirs/': {
      id: '/workdirs/'
      path: '/workdirs'
      fullPath: '/workdirs/'
      preLoaderRoute: typeof WorkdirsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workdirs': {
      id: '/api/workdirs'
      path: '/api/workdirs'
      fullPath: '/api/workdirs'
      preLoaderRoute: typeof ApiWorkdirsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workdirs/$workdirId/': {
      id: '/workdirs/$workdirId/'
      path: '/workdirs/$workdirId'
      fullPath: '/workdirs/$workdirId/'
      preLoaderRoute: typeof WorkdirsWorkdirIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workdirs/$id': {
      id: '/api/workdirs/$id'
      path: '/$id'
      fullPath: '/api/workdirs/$id'
      preLoaderRoute: typeof ApiWorkdirsIdRouteImport
      parentRoute: typeof ApiWorkdirsRoute
    }
    '/api/chats/$id': {
      id: '/api/chats/$id'
      path: '/api/chats/$id'
      fullPath: '/api/chats/$id'
      preLoaderRoute: typeof ApiChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workdirs/$workdirId/chats/$chatId': {
      id: '/workdirs/$workdirId/chats/$chatId'
      path: '/workdirs/$workdirId/chats/$chatId'
      fullPath: '/workdirs/$workdirId/chats/$chatId'
      preLoaderRoute: typeof WorkdirsWorkdirIdChatsChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workdirs/$id/upload': {
      id: '/api/workdirs/$id/upload'
      path: '/upload'
      fullPath: '/api/workdirs/$id/upload'
      preLoaderRoute: typeof ApiWorkdirsIdUploadRouteImport
      parentRoute: typeof ApiWorkdirsIdRoute
    }
    '/api/workdirs/$id/manifest': {
      id: '/api/workdirs/$id/manifest'
      path: '/manifest'
      fullPath: '/api/workdirs/$id/manifest'
      preLoaderRoute: typeof ApiWorkdirsIdManifestRouteImport
      parentRoute: typeof ApiWorkdirsIdRoute
    }
    '/api/workdirs/$id/download': {
      id: '/api/workdirs/$id/download'
      path: '/download'
      fullPath: '/api/workdirs/$id/download'
      preLoaderRoute: typeof ApiWorkdirsIdDownloadRouteImport
      parentRoute: typeof ApiWorkdirsIdRoute
    }
    '/api/workdirs/$id/chats': {
      id: '/api/workdirs/$id/chats'
      path: '/chats'
      fullPath: '/api/workdirs/$id/chats'
      preLoaderRoute: typeof ApiWorkdirsIdChatsRouteImport
      parentRoute: typeof ApiWorkdirsIdRoute
    }
    '/api/chats/$chatId/stream': {
      id: '/api/chats/$chatId/stream'
      path: '/api/chats/$chatId/stream'
      fullPath: '/api/chats/$chatId/stream'
      preLoaderRoute: typeof ApiChatsChatIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats/$chatId/message': {
      id: '/api/chats/$chatId/message'
      path: '/api/chats/$chatId/message'
      fullPath: '/api/chats/$chatId/message'
      preLoaderRoute: typeof ApiChatsChatIdMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chats/$chatId/cancel': {
      id: '/api/chats/$chatId/cancel'
      path: '/api/chats/$chatId/cancel'
      fullPath: '/api/chats/$chatId/cancel'
      preLoaderRoute: typeof ApiChatsChatIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiWorkdirsIdRouteChildren {
  ApiWorkdirsIdChatsRoute: typeof ApiWorkdirsIdChatsRoute
  ApiWorkdirsIdDownloadRoute: typeof ApiWorkdirsIdDownloadRoute
  ApiWorkdirsIdManifestRoute: typeof ApiWorkdirsIdManifestRoute
  ApiWorkdirsIdUploadRoute: typeof ApiWorkdirsIdUploadRoute
}

const ApiWorkdirsIdRouteChildren: ApiWorkdirsIdRouteChildren = {
  ApiWorkdirsIdChatsRoute: ApiWorkdirsIdChatsRoute,
  ApiWorkdirsIdDownloadRoute: ApiWorkdirsIdDownloadRoute,
  ApiWorkdirsIdManifestRoute: ApiWorkdirsIdManifestRoute,
  ApiWorkdirsIdUploadRoute: ApiWorkdirsIdUploadRoute,
}

const ApiWorkdirsIdRouteWithChildren = ApiWorkdirsIdRoute._addFileChildren(
  ApiWorkdirsIdRouteChildren,
)

interface ApiWorkdirsRouteChildren {
  ApiWorkdirsIdRoute: typeof ApiWorkdirsIdRouteWithChildren
}

const ApiWorkdirsRouteChildren: ApiWorkdirsRouteChildren = {
  ApiWorkdirsIdRoute: ApiWorkdirsIdRouteWithChildren,
}

const ApiWorkdirsRouteWithChildren = ApiWorkdirsRoute._addFileChildren(
  ApiWorkdirsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiWorkdirsRoute: ApiWorkdirsRouteWithChildren,
  WorkdirsIndexRoute: WorkdirsIndexRoute,
  ApiChatsIdRoute: ApiChatsIdRoute,
  WorkdirsWorkdirIdIndexRoute: WorkdirsWorkdirIdIndexRoute,
  ApiChatsChatIdCancelRoute: ApiChatsChatIdCancelRoute,
  ApiChatsChatIdMessageRoute: ApiChatsChatIdMessageRoute,
  ApiChatsChatIdStreamRoute: ApiChatsChatIdStreamRoute,
  WorkdirsWorkdirIdChatsChatIdRoute: WorkdirsWorkdirIdChatsChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
