/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkdirsIndexRouteImport } from './routes/workdirs/index'
import { Route as ApiWorkdirsRouteImport } from './routes/api/workdirs'
import { Route as WorkdirsWorkdirIdIndexRouteImport } from './routes/workdirs/$workdirId/index'
import { Route as ApiWorkdirsIdRouteImport } from './routes/api/workdirs.$id'
import { Route as ApiChatsIdRouteImport } from './routes/api/chats.$id'
import { Route as WorkdirsWorkdirIdChatsChatIdRouteImport } from './routes/workdirs/$workdirId/chats/$chatId'
import { Route as ApiWorkdirsIdManifestRouteImport } from './routes/api/workdirs.$id.manifest'
import { Route as ApiWorkdirsIdChatsRouteImport } from './routes/api/workdirs.$id.chats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkdirsIndexRoute = WorkdirsIndexRouteImport.update({
  id: '/workdirs/',
  path: '/workdirs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkdirsRoute = ApiWorkdirsRouteImport.update({
  id: '/api/workdirs',
  path: '/api/workdirs',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkdirsWorkdirIdIndexRoute = WorkdirsWorkdirIdIndexRouteImport.update({
  id: '/workdirs/$workdirId/',
  path: '/workdirs/$workdirId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkdirsIdRoute = ApiWorkdirsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkdirsRoute,
} as any)
const ApiChatsIdRoute = ApiChatsIdRouteImport.update({
  id: '/api/chats/$id',
  path: '/api/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkdirsWorkdirIdChatsChatIdRoute =
  WorkdirsWorkdirIdChatsChatIdRouteImport.update({
    id: '/workdirs/$workdirId/chats/$chatId',
    path: '/workdirs/$workdirId/chats/$chatId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkdirsIdManifestRoute = ApiWorkdirsIdManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => ApiWorkdirsIdRoute,
} as any)
const ApiWorkdirsIdChatsRoute = ApiWorkdirsIdChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => ApiWorkdirsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/workdirs': typeof ApiWorkdirsRouteWithChildren
  '/workdirs/': typeof WorkdirsIndexRoute
  '/api/chats/$id': typeof ApiChatsIdRoute
  '/api/workdirs/$id': typeof ApiWorkdirsIdRouteWithChildren
  '/workdirs/$workdirId/': typeof WorkdirsWorkdirIdIndexRoute
  '/api/workdirs/$id/chats': typeof ApiWorkdirsIdChatsRoute
  '/api/workdirs/$id/manifest': typeof ApiWorkdirsIdManifestRoute
  '/workdirs/$workdirId/chats/$chatId': typeof WorkdirsWorkdirIdChatsChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/workdirs': typeof ApiWorkdirsRouteWithChildren
  '/workdirs': typeof WorkdirsIndexRoute
  '/api/chats/$id': typeof ApiChatsIdRoute
  '/api/workdirs/$id': typeof ApiWorkdirsIdRouteWithChildren
  '/workdirs/$workdirId': typeof WorkdirsWorkdirIdIndexRoute
  '/api/workdirs/$id/chats': typeof ApiWorkdirsIdChatsRoute
  '/api/workdirs/$id/manifest': typeof ApiWorkdirsIdManifestRoute
  '/workdirs/$workdirId/chats/$chatId': typeof WorkdirsWorkdirIdChatsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/workdirs': typeof ApiWorkdirsRouteWithChildren
  '/workdirs/': typeof WorkdirsIndexRoute
  '/api/chats/$id': typeof ApiChatsIdRoute
  '/api/workdirs/$id': typeof ApiWorkdirsIdRouteWithChildren
  '/workdirs/$workdirId/': typeof WorkdirsWorkdirIdIndexRoute
  '/api/workdirs/$id/chats': typeof ApiWorkdirsIdChatsRoute
  '/api/workdirs/$id/manifest': typeof ApiWorkdirsIdManifestRoute
  '/workdirs/$workdirId/chats/$chatId': typeof WorkdirsWorkdirIdChatsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/workdirs'
    | '/workdirs/'
    | '/api/chats/$id'
    | '/api/workdirs/$id'
    | '/workdirs/$workdirId/'
    | '/api/workdirs/$id/chats'
    | '/api/workdirs/$id/manifest'
    | '/workdirs/$workdirId/chats/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/workdirs'
    | '/workdirs'
    | '/api/chats/$id'
    | '/api/workdirs/$id'
    | '/workdirs/$workdirId'
    | '/api/workdirs/$id/chats'
    | '/api/workdirs/$id/manifest'
    | '/workdirs/$workdirId/chats/$chatId'
  id:
    | '__root__'
    | '/'
    | '/api/workdirs'
    | '/workdirs/'
    | '/api/chats/$id'
    | '/api/workdirs/$id'
    | '/workdirs/$workdirId/'
    | '/api/workdirs/$id/chats'
    | '/api/workdirs/$id/manifest'
    | '/workdirs/$workdirId/chats/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiWorkdirsRoute: typeof ApiWorkdirsRouteWithChildren
  WorkdirsIndexRoute: typeof WorkdirsIndexRoute
  ApiChatsIdRoute: typeof ApiChatsIdRoute
  WorkdirsWorkdirIdIndexRoute: typeof WorkdirsWorkdirIdIndexRoute
  WorkdirsWorkdirIdChatsChatIdRoute: typeof WorkdirsWorkdirIdChatsChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workdirs/': {
      id: '/workdirs/'
      path: '/workdirs'
      fullPath: '/workdirs/'
      preLoaderRoute: typeof WorkdirsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workdirs': {
      id: '/api/workdirs'
      path: '/api/workdirs'
      fullPath: '/api/workdirs'
      preLoaderRoute: typeof ApiWorkdirsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workdirs/$workdirId/': {
      id: '/workdirs/$workdirId/'
      path: '/workdirs/$workdirId'
      fullPath: '/workdirs/$workdirId/'
      preLoaderRoute: typeof WorkdirsWorkdirIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workdirs/$id': {
      id: '/api/workdirs/$id'
      path: '/$id'
      fullPath: '/api/workdirs/$id'
      preLoaderRoute: typeof ApiWorkdirsIdRouteImport
      parentRoute: typeof ApiWorkdirsRoute
    }
    '/api/chats/$id': {
      id: '/api/chats/$id'
      path: '/api/chats/$id'
      fullPath: '/api/chats/$id'
      preLoaderRoute: typeof ApiChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workdirs/$workdirId/chats/$chatId': {
      id: '/workdirs/$workdirId/chats/$chatId'
      path: '/workdirs/$workdirId/chats/$chatId'
      fullPath: '/workdirs/$workdirId/chats/$chatId'
      preLoaderRoute: typeof WorkdirsWorkdirIdChatsChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workdirs/$id/manifest': {
      id: '/api/workdirs/$id/manifest'
      path: '/manifest'
      fullPath: '/api/workdirs/$id/manifest'
      preLoaderRoute: typeof ApiWorkdirsIdManifestRouteImport
      parentRoute: typeof ApiWorkdirsIdRoute
    }
    '/api/workdirs/$id/chats': {
      id: '/api/workdirs/$id/chats'
      path: '/chats'
      fullPath: '/api/workdirs/$id/chats'
      preLoaderRoute: typeof ApiWorkdirsIdChatsRouteImport
      parentRoute: typeof ApiWorkdirsIdRoute
    }
  }
}

interface ApiWorkdirsIdRouteChildren {
  ApiWorkdirsIdChatsRoute: typeof ApiWorkdirsIdChatsRoute
  ApiWorkdirsIdManifestRoute: typeof ApiWorkdirsIdManifestRoute
}

const ApiWorkdirsIdRouteChildren: ApiWorkdirsIdRouteChildren = {
  ApiWorkdirsIdChatsRoute: ApiWorkdirsIdChatsRoute,
  ApiWorkdirsIdManifestRoute: ApiWorkdirsIdManifestRoute,
}

const ApiWorkdirsIdRouteWithChildren = ApiWorkdirsIdRoute._addFileChildren(
  ApiWorkdirsIdRouteChildren,
)

interface ApiWorkdirsRouteChildren {
  ApiWorkdirsIdRoute: typeof ApiWorkdirsIdRouteWithChildren
}

const ApiWorkdirsRouteChildren: ApiWorkdirsRouteChildren = {
  ApiWorkdirsIdRoute: ApiWorkdirsIdRouteWithChildren,
}

const ApiWorkdirsRouteWithChildren = ApiWorkdirsRoute._addFileChildren(
  ApiWorkdirsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiWorkdirsRoute: ApiWorkdirsRouteWithChildren,
  WorkdirsIndexRoute: WorkdirsIndexRoute,
  ApiChatsIdRoute: ApiChatsIdRoute,
  WorkdirsWorkdirIdIndexRoute: WorkdirsWorkdirIdIndexRoute,
  WorkdirsWorkdirIdChatsChatIdRoute: WorkdirsWorkdirIdChatsChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
